### ISSUE TITLE
The time is using UTC in both app and DB

### ISSUE THREAD

**Issue by lydia-gu** [usydtechlab/etaki3d#5]
As described in title

**Comment by lydia-gu** [comment]
Fix steps:

In `.env` file, add:

```bash
# Timezone
APP_TIMEZONE=Australia/Sydney
```

In `config/app.php`, add:

```php
 'timezone' => env('APP_TIMEZONE', 'UTC'),
```

In `docker-compose.yml`:

```yml
db:
    image: postgres:${POSTGRES_VERSION:-latest}
    ... ...
    environment:
      TZ: "${APP_TIMEZONE}"
```
